# Descriptive Statistics in SAS


```{r mind map,echo = F,message = FALSE, error = FALSE, warning = FALSE}
library('mindr')
### text -> widget
### input <- c("# Chapter 1", "## Section 1.1", "### Section 1.1.1", "## Section 1.2", "# Chapter 2")
### mm(from = input, type = "text", root = "mindr")
filename <- rstudioapi::getSourceEditorContext()$path
widget <- mm(from = filename, type = "file", root = "")
widget
```



## PROC FREQ

```
PROC FREQ <options> ;

  BY variables;
  EXACT statistic-options </ computation-options> ;
  OUTPUT <OUT=SAS-data-set> output-options;
  TABLES requests </ options> ;
  TEST options;
  WEIGHT variable </ option> ;
```

### ODS Table Names

See more ["ODS Table Names"](https://documentation.sas.com/doc/en/statcdc/14.2/statug/statug_freq_details116.htm)

| ODS Table Name    | Description                            | Statement | Option           |
|-------------------|----------------------------------------|-----------|------------------|
| BinomialCLs       | Binomial confidence limits             | TABLES    | BINOMIAL(CL=)    |
| BinomialEquivTest | Binomial equivalence test              | TABLES    | BINOMIAL(EQUIV)  |
| BinomialNoninf    | Binomial noninferiority test           | TABLES    | BINOMIAL(NONINF) |
| BinomialTest      | Binomial proportion test               | TABLES    | BINOMIAL         |
| CMH               | Cochran-Mantel-Haenszel test           | TABLES    | CMH              |
| ChiSq             | Chi-square tests                       | TABLES    | CHISQ            |
| EqualKappaTests   | Tests for equal kappas                 | TABLES    | AGREE            |
| EqualOddsRatios   | Tests for equal odds ratios            | EXACT     | EQOR             |
| GammaTest         | Gamma test                             | TEST      | GAMMA            |
| LRChiSq           | Likelihood ratio chi-square exact test | EXACT     | LRCHI            |
| MHChiSq           | Mantel-Haenszel chi-square exact test  | EXACT     | MHCHI            |
| OneWayChiSq       | One-way chi-square test                | TABLES    | CHISQ            |
| PearsonCorr       | Pearson correlation                    | TEST      | PCORR            |


### ODS Plots

| ODS Graph Name | Description               | PLOTS= Option | TABLES Statement Option           |
|----------------|---------------------------|---------------|-----------------------------------|
| AgreePlot      | Agreement plot            | AGREEPLOT     | AGREE                             |
| CumFreqPlot    | Cumulative frequency plot | CUMFREQPLOT   | One-way table request             |
| DeviationPlot  | Deviation plot            | DEVIATIONPLOT | CHISQ (one-way table)             |
| FreqPlot       | Frequency plot            | FREQPLOT      | Any table request                 |
| KappaPlot      | Kappa plot                | KAPPAPLOT     | AGREE                             |
| MosaicPlot     | Mosaic plot               | MOSAICPLOT    | Two-way or multiway table request |
| ORPlot         | Odds ratio plot           | ODDSRATIOPLOT | MEASURES, OR, or RELRISK          |
| RelRiskPlot    | Relative risk plot        | RELRISKPLOT   | MEASURES or RELRISK               |
| RiskDiffPlot   | Risk difference plot      | RISKDIFFPLOT  | RISKDIFF ( table)                 |
| WtKappaPlot    | Weighted kappa plot       | WTKAPPAPLOT   | AGREE                             |
| PearsonCorr    | Pearson correlation       | TEST          | PCORR                             |


## PROC UNIVARIATE

### HISTOGRAM Statement

The HISTOGRAM statement creates histograms and optionally superimposes estimated **parametric and nonparametric** probability density curves. 

**ODS Tables Produced with the HISTOGRAM Statement**

| ODS Table Name     |                  Description                  |            Option            |
|--------------------|:---------------------------------------------:|:----------------------------:|
| Bins               |                 Histogram bins                | MIDPERCENTS secondary option |
| FitQuantiles       |        Quantiles of fitted distribution       |    Any distribution option   |
| GoodnessOfFit      | Goodness-of-fit tests for fitted distribution |    Any distribution option   |
| HistogramBins      |                 Histogram bins                |      MIDPERCENTS option      |
| ParameterEstimates |  Parameter estimates for fitted distribution  |    Any distribution option   |


### CDFPLOT Statement

The CDFPLOT statement plots the observed cumulative distribution function (CDF) of a variable The CDF is defined as
$$
\begin{aligned}
F_{N}(x) &=\text { percent of nonmissing values } \leq x \\
&=\frac{\text { number of values } \leq x}{N} \times 100 \%
\end{aligned}
$$

* [Distribution Options](https://documentation.sas.com/doc/it/pgmsascdc/9.4_3.5/procstat/procstat_univariate_syntax03.htm)
* General Options

```
proc univariate data=Steel;
   var Length Width;
   cdfplot Width / normal(mu=10 sigma=0.5);
run;
```

### PPPLOT Statement

The PPPLOT statement creates a probability-probability plot (also called a P-P plot or percent plot), which compares the empirical cumulative distribution function (ECDF) of a variable with a specified theoretical cumulative distribution function such as the normal. If the two distributions match, the points on the plot form a linear pattern that passes through the origin and has unit slope. 

Specify one of the following theoretical distributions

* beta
* exponential
* gamma
* Gumbel
* generalized Pareto
* inverse Gaussian
* lognormal
* normal
* ...
* Weibull

### PROBPLOT and QQPLOT Statement

The PROBPLOT statement creates a probability plot, which compares ordered variable values with the percentiles of a specified theoretical distribution. If the data distribution matches the theoretical distribution, the points on the plot form a linear pattern. Consequently, you can use a probability plot to determine how well a theoretical distribution models a set of measurements.

The QQPLOT statement creates quantile-quantile plots (Q-Q plots) and compares ordered variable values with quantiles of a specified theoretical distribution. If the data distribution matches the theoretical distribution, the points on the plot form a linear pattern. Thus, you can use a Q-Q plot to determine how well a theoretical distribution models a set of measurements.

### ODS Tables   

| ODS Table Name    |                         Description                         |              Option              |
|-------------------|:-----------------------------------------------------------:|:--------------------------------:|
| BasicIntervals    | Confidence intervals for mean, standard deviation, variance |              CIBASIC             |
| BasicMeasures     |             Measures of location and variability            |              Default             |
| ExtremeObs        |                     Extreme observations                    |              Default             |
| ExtremeValues     |                        Extreme values                       |             NEXTRVAL=            |
| Frequencies       |                         Frequencies                         |               FREQ               |
| LocationCounts    |        Counts used for sign test and signed rank test       |             LOCCOUNT             |
| MissingValues     |                        Missing values                       | Default, if missing values exist |
| Modes             |                            Modes                            |               MODES              |
| Moments           |                        Sample moments                       |              Default             |
| Plots             |                  Legacy line printer plots                  |               PLOTS              |
| Quantiles         |                          Quantiles                          |              Default             |
| RobustScale       |                   Robust measures of scale                  |            ROBUSTSCALE           |
| SSPlots           |          Legacy line printer side-by-side box plots         |     PLOTS (with BY statement)    |
| TestsForLocation  |                      Tests for location                     |              default             |
| TestsForNormality |                     Tests for normality                     |            NORMALTEST            |
| TrimmedMeans      |                        Trimmed means                        |             TRIMMED=             |
| WinsorizedMeans   |                       Winsorized means                      |            WINSORIZED=           |


### ODS Graphics

| ODS Graph Name | Plot Description | Statement |
|----------------|------------------|-----------|
| CDFPlot        | CDF plot         | CDFPLOT   |
| Histogram      | Histogram        | HISTOGRAM |
| PPPlot         | P-P plot         | PPPLOT    |
| ProbPlot       | Probability plot | PROBPLOT  |
| QQPlot         | Q-Q plot         | QQPLOT    |



## PROC MEANS

### Basic summary statistics

```
ods select none;
		proc means data=data_in  stackodsoutput n nmiss min max mean median std q1 q3 maxdec=3 completetypes missing order=data ; 
			var var1 ... CFB CFM1;	
			class classvar1 classvar2 ...;
			ods output  summary = data_out ; 
		run;
		ods select all;
```

### AUTONAME Option

```
proc means noprint proc
  data=x.electricity;
  class division serial;
  var kwh1 rev1;
  output out=new4 mean(kwh1) = sum(rev1) =/autoname;
run;
```


### CHARTYPE Option

By using the CHARTYPE option, the analyst easily creates the three desired data sets in a single use of PROC MEANS.

```
proc means noprint data=order.orderfile2 CHARTYPE;
  class mailcode deptnbr segment status;
  var itmprice itm_qty;
  output out=one(where=(_type = '1001')) sum=;
  output out=two(where=(type = '1011')) sum=;
  output out=three(where=(type = '0110')) sum = ;
run;
```

**DESCENDTYPES Option**

The new DESCENDTYPES option, which is placed in the PROC MEANS statement, instructs the procedure to order observations in the output data sets it creates in descending value of TYPE. This option is very handy if you want the observation with TYPE = 0 at the bottom of your data set, rather than at the top.


## PROC TABULATE 

### Basic Syntax for PROC TABULATE

```
 PROC TABULATE <option-list>;
   CLASS class-variable-list;
   VAR analysis-variable-list;
   TABLE <<page-expression,> row-expression,>
   column-expression </ table-option-list>;
   BY <NOTSORTED> <DESCENDING> variable-1
   < … <DESCENDING> variable-n>;
   FORMAT variable-list-1 format-1
   < … variable-list-n format-n>;
   FREQ variable;
   KEYLABEL keyword-1=‘description-1’
   < … keyword-n=“description-n’>;
   LABEL variable-1=‘label-1’ <…variable-n=‘label-n’>;
   WEIGHT variable;
 TITLE ‘text’;
```

### Identification of Desired Statistics

* N = the number of observations, the frequency count,
* MIN = the smallest value,
* MAX = the largest value,
* MEAN = the arithmetic mean, or the average,
* STD = the standard deviation,
* VAR = the variance,
* SUM = the sum of the values,
* PCTN = the percentage that one frequency is of another frequency,
* PCTSUM = the percentage that one sum is of another sum,

### In processing
