--- 
title: "As a Statistician"
author: "Zehui Bai"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This book involves different statistical principles and methods, including the application of SAS and R, and aims to accumulate personal statistical knowledge."
---

# Introduction



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


This book is more described in the form of notes, not in the way of scientific writing. The book aims to accumulate knowledge and codes (R, SAS) in statistical work and learning, so that the author has a firmer and systematic grasp of various analysis models and methods, and does not describe the basic concepts and definitions too much. 

The note is still being updated, and some chapters are left blank in order to add new content. The expected directory is as follows:
 
**The main content contains the following modules**:

* Data Management
    + Chap 01 Introduction
    + Chap 02 Input and Format
    + Chap 03 DM in SAS
    + Chap 04 DM in R
    + Chap 05 SQL (in processing)
    + Chap 06 
* Data Visualization
    + Chap 07 ggplot2
    + Chap 08 Proc Sqplot (in processing)
    + Chap 09
    + Chap 10
* Data Analysis
    + Chap 11 Descriptive Statistics in SAS
    + Chap 12 Descriptive Statistics in R
    + Chap 13 Sample Size Calculation
    + Chap 14 Parametric Test
    + Chap 15 ANOVA
    + Chap 16 Multiple Comparison
    + Chap 17 Non-Parametric Test
    + Chap 18 Correlation and Regression
    + Chap 19 Advanced Linear Regression
    + Chap 20 Logistic Regression 
    + Chap 21 Advanced Logistic Regression 
    + Chap 22 Survival Analysis
    + Chap 23 Advanced Survival Analysis
    + Chap 24 Count Data Regression
    + Chap 25
    + Chap 26 Mixed Model
    + Chap 27 Generalized Linear (Mixed) Model
    + Chap 28 Generalized Estimating Equation
    + Chap 29 Time Series Analysis (in processing)
    + Chap 30 Meta Analysis (in processing)
    + Chap 31 Group (Adaptive) Sequential Design
    + Chap 32 Clinic Study Design (in processing)
    + Chap 33 Propensity Score
    + Chap 34 Missing Data
<!--     + Chap 35 -->
<!--     + Chap 36 -->
<!--     + Chap 37 -->
<!-- * Machine learning and Deep learning (in processing) -->
<!--     + Chap 38 Bayesian Theory -->
<!--     + Chap 39 Bayesian Regression -->
<!--     + Chap 40 -->
<!--     + Chap 41 -->
<!--     + Chap 42 -->
<!--     + Chap 43 Regularization: Penalized Regression -->
<!--     + Chap 44 -->
<!--     + Chap 45 Classification Analysis -->
<!--     + Chap 46 Random Forest -->
<!--     + Chap 47 Gradient Descent and Gradient Boosting -->
<!--     + Chap 48 Cubist Model -->
<!--     + Chap 49 Support Vector Machine (SVM) -->
<!--     + Chap 50 K-Nearest Neighbors (KNN) -->
<!--     + Chap 51 Linear Discriminant Analysis (LDA) -->
<!--     + Chap 52 Multivariate Adaptive Regression Spline (MARS) -->
<!--     + Chap 53 Clustering Analysis -->
<!--     + Chap 54 -->
<!--     + Chap 55 -->
<!--     + Chap 56 Singular Value Decomposition (SVD) -->
<!--     + Chap 57 Principal Component Analysis (PCA) -->
<!--     + Chap 58 -->
<!--     + Chap 59 -->
<!--     + Chap 60 Neural Networks -->

    
